### ISSUE TITLE
Support Android NDK ?

### ISSUE THREAD

**Issue by ascorbic-acid** [philip82148/cpp-dump#93]
Thanks for this great tool, im wondering if we can use it with Android, below is how we log in android

Logger.h
```c++
//
//  Logger.h
//
//  Created by MJ (Ruit) on 1/1/19.
//

#ifndef Logger_h
#define Logger_h

// #include <jni.h>
#include <android/log.h>

enum LogType {
    oDEBUG = 3,
    oERROR = 6,
    oINFO  = 4,
    oWARN  = 5
};

// TAG is a prefix in front of log to help you filter logs
#define TAG "PJ: "
#define LOGD(...) ((void)__android_log_print(oDEBUG, TAG, __VA_ARGS__))
#define LOGE(...) ((void)__android_log_print(oERROR, TAG, __VA_ARGS__))
#define LOGI(...) ((void)__android_log_print(oINFO,  TAG, __VA_ARGS__))
#define LOGW(...) ((void)__android_log_print(oWARN,  TAG, __VA_ARGS__))

#endif /* Logger_h */
```

main.cpp
```c++
 int n = 5;
 LOGI("n: %d", n);
```

reference:
https://android.googlesource.com/platform/system/core/+/refs/heads/eclair-sholes-release2/include/android/log.h

**Comment by philip82148** [comment]
Thank you for your question!
I'm not an Android developer, but is it possible to use the library on Android with [this customization](https://github.com/philip82148/cpp-dump?tab=readme-ov-file#change-the-output-destination-from-the-standard-error-output)?
BTW, this feature is part of the next version (v0.7.0), which I plan to release in a few weeks.

**Comment by ascorbic-acid** [comment]
yes that feature work, i did not know about it, thanks

```cpp
template <>
void cpp_dump::write_log(std::string_view output) {
    LOGI("DUMP: %s", output);
}

```
